[uwsgi]
# The path to your Django project directory
chdir = /home/fszczepanski48/django_rest_api

# The module to run (point to your wsgi.py file)
module = foundyou_api.wsgi:application

# Set the virtual environment path (if using a virtualenv)
home = /home/fszczepanski48/django_rest_api/venv

# Number of worker processes
workers = 3

# Socket to bind (uWSGI communicates through sockets)
socket = 0.0.0.0:8000

# Set the process to run as
master = true

# Enable threads
threads = 2

# Enable logging
logto = /home/fszczepanski48/django_rest_api/uwsgi.log

# Set the Python path to include the Django project (sometimes needed for custom configurations)
pythonpath = /home/fszczepanski48/django_rest_api

# Set the WSGI application to be used
wsgi-file = /home/fszczepanski48/django_rest_api/foundyou_api/wsgi.py

# Optional: Set the env variable for Django settings module (if you need it)
env = DJANGO_SETTINGS_MODULE=foundyou_api.settings
