# Generated by Django 5.1.3 on 2025-03-03 21:08

from django.db import migrations

from fu_api.helpers.load_users import load_users, remove_users


def add_test_users(apps, schema_editor):
    load_users()


def remove_test_users(apps, schema_editor):
    remove_users()


class Migration(migrations.Migration):

    dependencies = [
        ("fu_api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_test_users, remove_test_users),
    ]
