# Generated by Django 5.1.3 on 2025-05-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fu_api', '0003_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='sender_and_receiver_must_be_different',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like',
        ),
    ]
