# Generated by Django 5.1.3 on 2025-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fu_api", "0004_seed_user1_relationships"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
