# Generated by Django 5.1.3 on 2025-03-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fu_api', '0004_alter_customuser_location_alter_event_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver', 'status')},
        ),
    ]
