# Generated by Django 5.1.3 on 2025-05-25 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fu_api', '0004_remove_like_sender_and_receiver_must_be_different_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
