# Generated by Django 5.1.3 on 2025-05-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fu_api', '0005_alter_like_receiver_alter_like_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('message', 'Message'), ('chat_invite', 'Chat Invite'), ('like', 'Like'), ('match', 'Match')], max_length=20),
        ),
    ]
