# Generated by Django 5.1.3 on 2025-05-26 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fu_api', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sent_match', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_match', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
