# Generated by Django 5.1.3 on 2024-12-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('Male', 'Mężczyzna'), ('Female', 'Kobieta')], default='Male', max_length=10),
        ),
    ]
