# Generated by Django 5.1.3 on 2025-01-04 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profileimage_image_alter_profileimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
