# Generated by Django 5.1.3 on 2025-01-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profileimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='app.location'),
            preserve_default=False,
        ),
    ]
