# Generated by Django 5.1.3 on 2025-01-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customuser_location_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(choices=[('Mężczyzna', 0), ('Kobieta', 1)], default=0),
        ),
    ]
