# Generated by Django 5.1.3 on 2025-01-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Mężczyzna'), (1, 'Kobieta')], default=0),
        ),
    ]
