# Generated by Django 5.1.3 on 2025-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
