# Generated by Django 5.1.3 on 2025-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_customuser_data_vector_customuser_rejected_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='data_vector',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Mężczyzna'), (1, 'Kobieta')]),
        ),
    ]
