# Generated by Django 5.1.3 on 2025-01-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_customuser_data_vector_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='app.location'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passions',
            field=models.JSONField(default=list),
        ),
    ]
