# Generated by Django 5.1.3 on 2025-01-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_customuser_location_alter_customuser_passions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='account_creation_date',
            new_name='created_at',
        ),
    ]
