# Generated by Django 5.1.3 on 2025-01-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_customuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sex',
            new_name='sex_id',
        ),
    ]
